// @generated by scripts/sync-version.mjs — do not edit by hand.
// Run `npm run sync-version` after bumping package.json.

/**
 * @quicknode/mpp package version. Used in the `x-qn-client` header sent
 * with every default-transport request. Statically defined so the module
 * loads in environments without a filesystem (Cloudflare Workers, edge).
 */
export const VERSION: string = '0.1.0'
