import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const dir = dirname(fileURLToPath(import.meta.url))
const pkgPath = join(dir, '..', 'package.json')
const targetPath = join(dir, '..', 'src', 'internal', 'version.ts')

const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'))

const generated = `// @generated by scripts/sync-version.mjs — do not edit by hand.
// Run \`npm run sync-version\` after bumping package.json.

/**
 * @quicknode/mpp package version. Used in the \`x-qn-client\` header sent
 * with every default-transport request. Statically defined so the module
 * loads in environments without a filesystem (Cloudflare Workers, edge).
 */
export const VERSION: string = '${pkg.version}'
`

writeFileSync(targetPath, generated)
console.log(`wrote src/internal/version.ts with VERSION='${pkg.version}'`)
